apiVersion: apps/v1
kind: Deployment
metadata:
  name: matan-app
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: matan-app
  template:
    metadata:
      labels:
        app: matan-app
    spec:
      containers:
      - name: matan-app
        image: matanzh/web-app:8.0  # Specify your Docker image
        ports:
        - containerPort: 5001  # Port your Flask app is listening on

